CREATE DATABASE DeDe;
USE DeDe;

CREATE TABLE `DeDe` (
  `id` Int( 11 ) AUTO_INCREMENT NOT NULL,
  `drinks` VARCHAR( 255) NOT NULL,
  `abv` VARCHAR(255) NOT NULL,
  `calories` VARCHAR( 255 ) NOT NULL,
  `created_at` DATETIME NOT NULL,

  PRIMARY KEY ( `id` ) 
);